### ISSUE TITLE
the paper is not available at the link provided.

### ISSUE THREAD

**Issue by rsindper** [oflynned/CS7434-Snapchat-Filter#3]
Hi there,

The paper is not available at the link provided (https://syzible.com/snapchat-filters.pdf). Is there anywhere to get the paper? If it is not available publicly, is it possible to send the paper to me by email (1094330504@qq.com)? Huge thanks!

**Comment by oflynned** [comment]
Available on https://me.syzible.com/snapchat-filters.pdf
